version: '3'
services:
  db:
    image: postgres:11.6-alpine
    ports:
      - "8001:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=LetsImagineThisPasswordIsSecure
      - POSTGRES_DB=nest
    restart: always

  web:
    build: ./web
    ports:
      - "3000:3000"
    container_name: web-docker
    restart: always
    links:
      - api

  api:
    build: ./api
    ports:
      - "8000:8000"
    container_name: api-docker
    restart: always
    depends_on:
      - db
    links:
      - db